name: uniqcast_code_challenge
description: "A code challenge task for uniqcast"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  freezed: 2.5.2
  freezed_annotation: ^2.4.4
  get_it: ^8.0.3
  go_router: ^14.7.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: null
  injectable: ^2.5.0
  internet_connection_checker: ^3.0.1
  intl: ^0.20.2
  json_annotation: 4.9.0
  json_serializable: 6.8.0
  mockito: ^5.4.2
  path_provider: ^2.1.5
  riverpod_annotation: ^2.6.1
  xml: ^6.5.0
  collection: 1.18.0
  hooks_riverpod: ^2.6.1
dev_dependencies:
  build_runner: 2.4.11
  custom_lint: ^0.7.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  hive_test: ^1.0.1
  injectable_generator: ^2.6.1
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3
  riverpod_test: ^0.1.6
  flutter_hooks: ^0.20.5
  flutter_local_notifications: ^16.3.0
  timezone: 0.9.0
  test: 1.25.6

flutter:
  uses-material-design: true
